<?php echo $this->render('header.phtml'); ?>
<div id="content">
	<div id="colLeft">
		<h1>Kontakt</h1>
<!-- 
		<span style="color: #C40524;">www:</span>
		http://fontini.domimedia.com.pl <br /> <span style="color: #C40524;">e-mail:</span>
		biuro@domimedia.pl <br /> <br /> <span style="color: #C40524;">Siedziba
			firmy</span> <br /> Office Promotion <br /> ul. Wróblewskiego 19A <br />
		90-001 Łódz <br /> tel. +48 42 682 31 02 <br />tel. kom. 604 77 95 95
		<br />tel./fax +48 42 682 31 02 <br /> czynne od poniedziałku do
		piątku <br />w godz.09:00-17:00<br />
		 -->
		 <?php $tekst = str_replace('\\', '', $this->statyczne[3]->tresc); echo $tekst; ?>
	</div>


	<div id="colRight">
		<div id="text">
			<h1>Kontakt</h1>
			Masz pytania lub sugestie związane ze stroną? Napisz do nas:
			<script
				src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
				type="text/javascript" charset="utf-8"></script>
			<script
				src="http://mgroup.pl/library/uniform/jquery.uniform.js"
				type="text/javascript" charset="utf-8"></script>
			<script type="text/javascript" charset="utf-8">
      $(function(){
        $("input, textarea, select, button").uniform();
      });
    </script>
			<link rel="stylesheet"
				href="http://mgroup.pl/library/uniform/css/uniform.default.css"
				type="text/css" media="screen">

			<form action="<?php echo $this->baseUrl;?>/kontakt" method="post" name="kontakt" >
				<table>
					<tr>
						<td><label>Wiadomość:</label></td>
						<td><textarea name="tresc" cols="40" rows="5"></textarea></td>
					</tr>
					<tr>
						<td><label>Podpis:</label></td>
						<td><input name="tytul" type="text" size="40" /></td>
					</tr>
					<tr>
						<td><label>E-mail:</label></td>
						<td><input name="mail" type="email" size="40" /></td>
					</tr>
					<tr>
						<td><label>Jak nas znalazłeś?:</label></td>
						<td><select name="skad">
								<option>Wyszukiwarka Google</option>
								<option>Przekierowanie z innej strony</option>
								<option>Inne</option>
						</select></td>
					</tr>
					<tr>
						<td></td>
						<td><input type="checkbox" name="odp" value="tak"/> <label>Czekam na odpowiedź</label></td>
					</tr>
					<tr>
						<td></td>
						<td><input type="submit" value="Wyślij" /> <input type="reset" value="Wyczyść" /></td>
					</tr>
				</table>
			</form>
<script language="JavaScript">
   	var sprawdzacz = new Validator("kontakt");
   	sprawdzacz.addValidation("tytul","req","Wprowadź imię i nazwisko");
   	sprawdzacz.addValidation("tytul","maxlen=40","Podpis nie może być dłuższy niż 40 znaków");

   	sprawdzacz.addValidation("mail","req","Podaj adres e-mail w polu pod imieniem i nazwiskiem");
   	sprawdzacz.addValidation("mail","maxlen=60","Błąd - adres e-mail dłuższy niż 60 znaków");
   	sprawdzacz.addValidation("mail","email","Niepoprawny adres e-mail");

   	sprawdzacz.addValidation("tresc","maxlen=2000","Formularz nie przyjmuje wiadomości dłuższych niż 2000 znaków");
   	sprawdzacz.addValidation("tresc","req","Wprowadź treść wiadomości");
   </script>


		</div>
	</div>



	<!--  
		<div id="colRight">
			<div id="text">
			<iframe width="600" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.pl/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=%C5%82%C3%B3d%C5%BA,+wr%C3%B3blewskiego+19A&amp;aq=&amp;sll=52.025459,19.204102&amp;sspn=6.897864,21.643066&amp;ie=UTF8&amp;hq=&amp;hnear=Genera%C5%82a+Walerego+Wr%C3%B3blewskiego+19A,+%C5%81%C3%B3d%C5%BA,+%C5%82%C3%B3dzkie&amp;t=m&amp;ll=51.746044,19.44932&amp;spn=0.00465,0.012875&amp;z=16&amp;output=embed"></iframe><br />
		</div>
		</div>
		-->
</div>
<?php echo $this->render('footer.phtml'); ?>