<div id="footer">
		<div style="float: left;">
			<a href="<?php echo $this->baseUrl;?>/" title="#"><img src="<?php echo $this->baseUrl;?>/images/up.png" alt="#" title="#" name="#" /></a>
		</div>
		<div style="float: left; padding: 15px 0px 0px 5px;">
			Copyrights © 2012 <a href="<?php echo $this->baseUrl;?>/" title="Fontini">Fontini</a>.<br /> 
			Wszelkie prawa zastrzeżone.<br />
			<br />
			Projekt i wykonanie: <a href="http://mgroup.pl/" target="_blank">MGroup</a>.
		</div>
		<div style="float: left; padding: 10px 0px 0px 60px;"> <img src="<?php echo $this->baseUrl;?>/images/znaczki/f.png" alt="#" title="#" name="#" /> <img src="<?php echo $this->baseUrl;?>/images/znaczki/g.png" alt="#" title="#" name="#" /> <img src="<?php echo $this->baseUrl;?>/images/znaczki/t.png" alt="#" title="#" name="#" /> <img src="<?php echo $this->baseUrl;?>/images/znaczki/nk.png" alt="#" title="#" name="#" /></div>
		<div style="float: right; padding-top: 20px;">
			<a href="<?php echo $this->baseUrl;?>/">Strona Główna</a> - <a href="<?php echo $this->baseUrl;?>/onas">O nas</a> - <a href="<?php echo $this->baseUrl;?>/produkty">Produkty</a> - <a href="http://sklep.domimedia.pl/index-pct-744.html">Sklep</a> - <a href="<?php echo $this->baseUrl;?>/galeria">Galeria</a> - <a href="<?php echo $this->baseUrl;?>/projektanci">Projektanci</a> - <a href="<?php echo $this->baseUrl;?>/newsletter">Newsletter</a> - <a href="<?php echo $this->baseUrl;?>/kontakt">Kontakt</a>
		</div>
	</div>
</div>
</body>
</html>