<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>FONTINI</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name='keywords' content='FONTINI' />
<meta name='description' content='FONTINI' />
<meta property="fb:admins" content="1532218504"/>
<link rel="shortcut icon" href="<?php echo $this->baseUrl;?>/images/fontini.ico" type="image/x-icon"/>
	<link href="<?php echo $this->baseUrl;?>/styles/style_fontini.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/library/javavalid/gen_validatorv2.js" type="text/javascript"></script>
<script type="text/javascript">



	  var _gaq = _gaq || [];

	  _gaq.push(['_setAccount', 'UA-7337540-4']);

	  _gaq.push(['_trackPageview']);



	  (function() {

	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

	  })();



	</script>
	</head>

	<body>
<div id="container">
	<div id="header">
		<div id="menu">
			<ul>
				<li><a href="<?php echo $this->baseUrl;?>/" title="Strona Główna" name="#">Strona Główna</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/onas" title="O NAS" name="#">O nas</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/produkty" title="PRODUKTY" name="#">Produkty</a></li>
			</ul>
		</div>
		<div id="logo">
			<a href="<?php echo $this->baseUrl;?>/" title="#" name="#"><img src="<?php echo $this->baseUrl;?>/images/logo.png" alt="#" title="#" name="#" /></a>
		</div>
		<div id="menu2">
		<ul>
				<li><a href="http://sklep.domimedia.pl/index-sid-27-cat-10376-catarr-10377_10376-pct-744-cfp.html" title="SKLEP" name="#" target="_blank">Sklep</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/galeria" title="GALERIA" name="#">Galeria</a></li>
				<li><a href="<?php echo $this->baseUrl;?>/kontakt" title="KONTAKT" name="#">Kontakt</a></li>
				</ul>
		</div>
	</div>