<div style="width:100%">

    <div style=" margin-top: 15px; float:right; ">
       
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
               <div class="pagination"><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></div>
            <?php else: ?>
                <?= '<div class="pagination2">'.$page.'</div>'; ?>
            <?php endif; ?>
        <?php endforeach; ?>
       <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <div class="pagination3"><a href="<?= $this->url(array('page' => $this->last)); echo '">... z '.$this->last; ?></a></div>
        <?php else: ?>
            <span class="disabled"></span>
        <?php endif; ?>
         <!--&nbsp; Page <?= $this->current; ?> of <?= $this->last; ?>-->
    </div>
 </div>