<?php echo $this->render('header.phtml'); ?>
<div id="content">
		<?php echo $this->render('lewa.phtml'); ?>
		<div id="colRight">
			<div id="text">
				<h1>Produkty marki Fontini</h1>
				FONTINI to marka, która istnieje na rynku już od ponad 50 lat produkując przepiękne wyłączniki i kontakty.<br/> Dzięki zespołowi utalentowanych projektantów, hiszpańska firma FONTINI oferuje najwyższej jakości produkty. <br/>Widać w nich prawdziwą pasję i zaangażowanie osób, które je stworzyły. <br/>Dzięki tym stylowym drobiazgom wnętrza nabierają niepowtarzalnego charakteru łącząc luksus, piękno i znakomite wykonanie. <br/>Każdy wyłącznik FONTINI to niezwykła forma, zaskakujące materiały (szkło, porcelana, drewno, stal, mosiądz) i ogromny wybór kolorów. 
<br/>Do wnętrz pałacowych, starych dworków, ale też do nowoczesnych apartamentów nie znajdziecie Państwo niczego bardziej odpowiedniego.
<br/><br/>
GARBY i GARBY COLONIAL<br/>
Garby i Garby Colonial to kolekcja dla osób, które chciałyby w swoim wnętrzu przywołać klimat dawnych czasów. Ci którzy pamiętają mieszkania swoich babć docenią niezwykły urok porcelanowych pstryczków. Można zaprojektować własne przełączniki dobierając odpowiednią ramkę i mechanizm. Garby Colonial to prawdziwa rozkosz osób, które w wystroju wnętrza doceniają detale.
<br/><br/>
VENEZIA<br/>
Venezia to kolekcja inspirowana jednym z najpiękniejszych miast na świecie. Swoją stylistyką przywodzi na myśl cudowne weneckie pałace z całą gamą rozmaitych zdobień i architektonicznych detali. Ta kolekcja to jak zaproszenie do zabawy w projektanta; ilość kształtów, kolorów i materiałów wykorzystywanych w Venezi jest ogromna. Dzięki temu można stworzyć niepowtarzalne przełączniki, które nadadzą wnętrzu jedyny w swoim rodzaju styl. Połącz porcelanę z drewnem, i metalem, a uzyskasz efekt, który zachwyci każdego.
<br/><br/>
F37<br/>
Wyłączniki z serii F-37 to czystość formy którą prezentuje firma Fontini. Są one inspirowane minimalistycznymi proporcjami i prostymi liniami. F-37 to seria w której metalowe wyłączniki zarówno obrotowe jak i dźwigniowe w doskonałej harmonii pasują do drewnianych czy szklanych ramek z tej samej serii. Wyłączniki z kolekcji F-37 zdecydowanie będą pasowały do Twojego nowoczesnego wnętrza.
<br/><br/>
DIMBLER<br/>
Dimbler to połączenie wiejskiego stylu z wyrafinowaną, dyskretną elegancją. Podobnie wyglądają dzwonki w recepcjach starych angielskich pensjonatów. Niektórzy projektanci wnętrz wykorzystują kolekcję Dimbler w nowoczesnych wnętrzach doceniając jej minimalizm i niepowtarzalność tych metalowych bądź porcelanowych przełączników. Znakomicie prezentują się też w drewnianej ramce razem z porcelanowym gniazdem.
<br/><br/>

1950<br/>
Kolekcja 1950 powstała by uczcić 50–lecie marki FONTINI. Swoim stylem nawiązuje do pierwszych seri z lat 50-tych. Charakterystyczne cech tej kolekcji to prostota i niezwykła elegancja. Wykonane z nawyższej jakości stali bądź mosiądzu przełączniki wnoszą powiew luksusu do każdego domu. Dostępne są w kilku rodzajach wykończeń: złotym, srebrnym, antycznym brązie, antracycie i graficie dają nieograniczone możliwości kreowania stylowego wnętrza. 
			</div>
		</div>
	</div>
<?php echo $this->render('footer.phtml'); ?>
