<?php echo $this->render('header.phtml'); ?>
<div id="fb-root"></div>  
<script>  
  window.fbAsyncInit = function() {  
    FB.init({  
      appId  : '106364959503867',  
      status : true, // czy ma sprawdzać logowanie  
      cookie : true, // uruchomienie cookiesów do sesji  
      xfbml  : true  // parsowanie XFBML  
    });  
  };  
  
  (function() {  
    var e = document.createElement('script');  
    e.src = document.location.protocol + '//connect.facebook.net/pl_PL/all.js';  
    e.async = true;  
    document.getElementById('fb-root').appendChild(e);  
  }());  
</script> 
<div id="content">
		<?php echo $this->render('lewa.phtml'); ?>
		<div id="colRight">
			<div id="text">
				<h1><?php echo $this->myk->tytul;?></h1>
				<script src="http://connect.facebook.net/pl_PL/all.js#xfbml=1"></script><fb:like href="http://www.mgroup.pl/fontini/aktualnosci/news/id/<?php echo $this->myk->id;?>" send="false" width="550" show_faces="false" font=""></fb:like>
				<br/><br/>
				<?php $wynik = str_replace('src="/fontini/images/', 'src="/images/', str_replace('\\', '', $this->myk->tresc));
				echo $wynik;?>
				<br/><br/>
				<div align="center">
            <div id="fb-root"></div><script src="http://connect.facebook.net/pl_PL/all.js#xfbml=1"></script><fb:comments href="http://www.mgroup.pl/fontini/aktualnosci/news/id/<?php echo $this->myk->id;?>" num_posts="10" width="600"></fb:comments>
		</div>
			</div>
		</div>
	</div>
<?php echo $this->render('footer.phtml'); ?>
