<?php echo $this->render('admin/mcms.phtml'); ?>
		<div id="content">
			<div class="content_buttons">
				<ul>
					<a href="<?php echo $this->baseUrl;?>/admin/aktualnosci"><li><input class="content_buttons_new" value="Nowa publikacja" /></li></a>
					<a href="<?php echo $this->baseUrl;?>/admin/aktualnoscilista"><li><input class="content_buttons_list" value="Lista publikacji" /></li></a>
				<ul>
			</div>
			<div class="content_title">
				aktualnosci
			</div>
			<div class="content_info">
				aktualnosci / dodaj pozycję
			</div>
			<div class="content_text">
				<div class="content_options">
					<div class="publikacje_select">
						
					</div>
					<div class="publikacje_id">
						
					</div>
					<div class="publikacje_title">
						
					</div>
					<div class="publikacje_publish2">
						
					</div>
					<div class="publikacje_date">
						
					</div>	
					<div class="publikacje_options">
					
					</div>
				</div>
				
				
				<form action="<?php echo $this->baseUrl;?>/admin/aktualnosci" method="post">
		<span class="czcionka_14 czcionka_zolta">Wpisz tytuł</span><br/>
		<input style="border: 1px solid threedshadow; width:700px;" type="text" name="nazwa" value=""/><br/>
		<br/>
		<span class="czcionka_14 czcionka_zolta">Treść</span><br/>
		<textarea id="editor2" class="ckeditor"  name="tresc"></textarea>
		<br/>
		<div align="center">
		<input type="submit" value="ZAPISZ!"/>
		</div>
		<br /><br />
   </form>
      <script type="text/javascript">

// This is a check for the CKEditor class. If not defined, the paths must be checked.
if ( typeof CKEDITOR == 'undefined' )
{
	document.write(
		'<strong><span style="color: #ff0000">Error</span>: CKEditor not found</strong>.' +
		'This sample assumes that CKEditor (not included with CKFinder) is installed in' +
		'the "/ckeditor/" path. If you have it installed in a different place, just edit' +
		'this file, changing the wrong paths in the &lt;head&gt; (line 5) and the "BasePath"' +
		'value (line 32).' ) ;
}
else
{
	var editor = CKEDITOR.replace( 'editor2' );

	// Just call CKFinder.SetupCKEditor and pass the CKEditor instance as the first argument.
	// The second parameter (optional), is the path for the CKFinder installation (default = "/ckfinder/").
	CKFinder.setupCKEditor( editor, '../ckfinder/' ) ;

	// It is also possible to pass an object with selected CKFinder properties as a second argument.
	// CKFinder.SetupCKEditor( editor, { BasePath : '../../', RememberLastFolder : false } ) ;
}

		</script>
				<div class="content_line3">
					<div class="publikacje_select">
						
					</div>
					<div class="publikacje_zaznaczone">
					
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>