<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
	<title>MCMS - System zarządzania treścią</title>
	<META HTTP-EQUIV="Content-Language" content="pl">
	<meta http-EQUIV="Content-Type" content="text/html; charset=UTF-8">  
<link rel="shortcut icon" href="<?php echo $this->baseUrl;?>/img/m.ico" type="image/x-icon"/>
	<style type="text/css" media="all">@import "http://www.mgroup.pl/mcms/mcms.css";</style>
</head>

<body>
<div class="login">
		<div class="logo">
			<img width="200px" src="http://www.mgroup.pl/mcms/images/logo.png" />
		</div>
		<div class="login2">
<form method="post" name="login" action="<?php echo $this->baseUrl?>/admin/login"> 
<b>Login:</b>
	<input name="login" class="input" type="text" value=""/> <br/>
    <b>Hasło:</b>
	<input name="haslo" class="input" type="password" value=""/><br/>
	<input type="submit"  class="input2" name="submit" value=""/> 
	</form> 
		</div>
	</div>
</body>
</html>