<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>MCMS</title>
	<style type="text/css" media="all">@import "<?php echo $this->baseUrl;?>/mcms/cms_style.css";</style>
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js" ></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js" ></script>
<script language="JavaScript" src="<?php echo $this->baseUrl;?>/styles/javavalid/gen_validatorv2.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/ckfinder/ckfinder.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">

function BrowseServer( startupPath, functionData )
{
	// You can use the "CKFinder" class to render CKFinder in a page:
	var finder = new CKFinder();

	// The path for the installation of CKFinder (default = "/ckfinder/").
	finder.basePath = '/';

	//Startup path in a form: "Type:/path/to/directory/"
	finder.startupPath = startupPath;

	// Name of a function which is called when a file is selected in CKFinder.
	finder.selectActionFunction = SetFileField;

	// Additional data to be passed to the selectActionFunction in a second argument.
	// We'll use this feature to pass the Id of a field that will be updated.
	finder.selectActionData = functionData;

	// Name of a function which is called when a thumbnail is selected in CKFinder.
	finder.selectThumbnailActionFunction = ShowThumbnails;

	// Launch CKFinder
	finder.popup();
}

// This is a sample function which is called when a file is selected in CKFinder.
function SetFileField( fileUrl, data )
{
	document.getElementById( data["selectActionData"] ).value = fileUrl;
}

// This is a sample function which is called when a thumbnail is selected in CKFinder.
function ShowThumbnails( fileUrl, data )
{
	// this = CKFinderAPI
	var sFileName = this.getSelectedFile().name;
	document.getElementById( 'thumbnails' ).innerHTML +=
			'<div class="thumb">' +
				'<img src="' + fileUrl + '" />' +
				'<div class="caption">' +
					'<a href="' + data["fileUrl"] + '" target="_blank">' + sFileName + '</a> (' + data["fileSize"] + 'KB)' +
				'</div>' +
			'</div>';

	document.getElementById( 'preview' ).style.display = "";
	// It is not required to return any value.
	// When false is returned, CKFinder will not close automatically.
	return false;
}
	</script>
</head>

<body>
<div id="container">
	<div id="colLeft">
		<div id="header">
			<a href="http://www.mgroup.pl" target="_blank"><img src="<?php echo $this->baseUrl;?>/mcms/images/logo.png" alt="" name="" title="" /></a>
		</div>
		<div id="user">
			<div class="user_avatar">
				<img src="<?php echo $this->baseUrl;?>/mcms/images/avatar.png" alt="" name="" title="" />
			</div>
			<div class="user_info">
				Witaj FONTINI<br />
				<div class="user_info_event">0</div> nowe zdarzenia<br />
				Zapraszamy do edycji :)<br />
			</div>
			<div class="user_buttons">
				<input type="submit" value="" class="user_buttons_settings" />
				<a href="<?php echo $this->baseUrl;?>/admin/logout"><input type="submit" value="" class="user_buttons_logout" /></a>
			</div>
		</div>
		<div id="panel">
			<div class="panel_title">Panel administracyjny</div>
			<ul>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujglowna"><li class="panel_publikacje">Strona główna</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/aktualnoscilista"><li class="panel_newsletter">Aktualności</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujonas"><li class="panel_uzytkownicy">O Nas</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujprodukty"><li class="panel_newsletter">Produkty</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/produktylista"><li class="panel_szkolenia">Produkty Lista</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujprojektanci"><li class="panel_partnerzy">Projektanci</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/galerielista"><li class="panel_promocje">Galerie</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujkontakt"><li class="panel_komentarze">Kontakt</li></a>
				
				<?php /*
				<a href="<?php echo $this->baseUrl;?>/admin/edytujdolacz"><li class="panel_szkolenia">Dołącz do nas</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujgaleria"><li class="panel_partnerzy">Galeria</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujzespol"><li class="panel_uzytkownicy">Nasz zespół</li></a>
				<a href="<?php echo $this->baseUrl;?>/admin/edytujpromocje"><li class="panel_promocje">Promocje</li></a>
				*/ ?>
			</ul>
		</div>
		<div id="footer">
			<ul>
				<li>© 2011 <b>MCMS by MGroup</b>. Wszelkie prawa zastrzeżone.</li>
			</ul>
		</div>
	</div>
	<div id="colRight">
		<div id="logo">
			<a href="http://fontini.domimedia.com.pl/" target="_blank"><img src="<?php echo $this->baseUrl;?>/mcms/images/niania.png" alt="" name="" title="" /></a>
		</div>