<?php echo $this->render('header.phtml'); ?>
<div id="fb-root"></div>  
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1&appId=106364959503867";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="content">
		<div id="colLeft">
			<h1>Galeria</h1>
			<ul>
			<?php for($i=0;$i<count($this->galerie);$i++){
			echo '<li><a href="'.$this->baseUrl.'/galeria/index/id/'.$this->galerie[$i]->id.'" title="'.$this->galerie[$i]->nazwa.'">'.$this->galerie[$i]->nazwa.'</a></li>';
			}?>
			</ul>
		</div>
		<div id="colRight">
			<div id="text">
				<h1><?php echo $this->myk->nazwa;?></h1>
				<script src="http://connect.facebook.net/pl_PL/all.js#xfbml=1"></script><fb:like href="http://fontini.domimedia.com.pl/aktualnosci/news/id/<?php echo $this->myk->id;?>" send="false" width="550" show_faces="false" font=""></fb:like>
				<br/><br/>
				<?php $wynik = str_replace('src="/fontini/images/', 'src="/images/', str_replace('\\', '', $this->myk->tresc));
				echo $wynik;?>
				<br/><br/>
				<div align="center">
				<div class="fb-comments" data-href="http://fontini.domimedia.com.pl/aktualnosci/news/id/<?php echo $this->myk->id;?>" data-num-posts="10" data-width="600"></div>
		</div>
			</div>
		</div>
	</div>
<?php echo $this->render('footer.phtml'); ?>
